name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t raks25/college-website:latest .

    - name: Push Docker Image
      run: |
        docker push raks25/college-website:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/college-website-deployment \
        college-website=raks25/college-website:latest

        kubectl rollout status deployment/college-website-deployment